### ISSUE TITLE
Not working on Safari

### ISSUE THREAD

**Issue by runemadsen** [runemadsen/rune.js#1]
[Error] SyntaxError: Cannot declare a parameter named 'text' as it shadows the name of a strict mode function.

Looks like a Babel issue:
https://github.com/babel/babel/issues/1121

**Comment by pr1ntr** [comment]
does this mean the whole lib just doesn't work on safari?

**Comment by runemadsen** [comment]
I believe so. Keep in mind this is a VERY young library that was just released, and is not used in production anywhere (as far as I know).

**Comment by danielmcq** [comment]
It's not that Safari isn't capable of doing the things that rune.js does, it's that rune.js is written in ES6 and to make it run on all of the browsers that don't support ES6, it's transpiled to ES5 using Babel. However, the ES5 code which Babel produces doesn't play well with Safari, because Safari is the new IE :(

**Comment by pr1ntr** [comment]
'... because Safari is the new IE :(' truer words have not been spoken.

**Comment by runemadsen** [comment]
I just spent a little while adding workarounds for this, and all tests are passing in Safari for version `0.2.5` that I just released. Thanks for reporting this! :+1:
