### ISSUE TITLE
Rune.js for Cycle.js and a few more Questions

### ISSUE THREAD

**Issue by HighOnDrive** [runemadsen/rune.js#3]
It's great to see that Rune.js uses the Virtual-DOM. Cycle.js is a leading edge framework for FRP based on RxJS that also uses Virtual-DOM. It would be awesome to get some integration between Cycle.js and Rune.js. Would this be an interest? See http://cycle.js.org

Super to see that Opentype.js is a dependency, in what example is it used? Is there support for rendering glyphs using Opentype.js with the new ES6 Unicode syntax?

Is there support for making layers, or would this just be done with standard SVG? Layers are the trend in modern UI's and are also useful for only updating changing foreground vs. background scenes, etc.

Is there an option of rendering to the HTML5 Canvas element and not only to SVG? Recently D3 developers have opted for Canvas rendering due to performance, plus the 2D Canvas has some great abilities that SVG does not. For example, see https://github.com/moebiolabs/moebio_framework

Also, would Lodash.js not be a more modern alternative to Underscore.js?

**Comment by runemadsen** [comment]
Hi @HighOnDrive 

Just some quick answers to your questions:

- Adding `opentype` to this repo was a mistake and will be fixed in the new release. I'm writing a `Rune.Font` plugin this week that will allow loading and manipulating font vectors. So that will use `opentype`
- I'm not sure exactly what you mean by layers, but there is `Rune.Group` which is basically layer functionality.
- I specifically chose this library to be in SVG, as I use it for making generative designs for print and need vector output. See more in the [about section](http://runemadsen.github.io/rune.js/about.html). However, the renderer is pretty agnostic and it should be a 1-day project to render to canvas too. I'm just not personally that interested in it right now.
- Yup, I should probably use lodash.

Thanks!

**Comment by HighOnDrive** [comment]
That sounds great! Thanks and I'll have a look at the canvas possibilities :+1:
